name: "deepmet"
platform: "onnxruntime_onnx"
version_policy {
  all {
  }
}
max_batch_size: 100
input [{
  name: "input"
  data_type: TYPE_FP32
  dims: [4500, 8]
}, {
  name: "input_cat0"
  data_type: TYPE_FP32
  dims: [4500, 1]
}, {
  name: "input_cat1"
  data_type: TYPE_FP32
  dims: [4500, 1]
}, {
  name: "input_cat2"
  data_type: TYPE_FP32
  dims: [4500, 1]
}]
output [{
  name: "output/BiasAdd"
  data_type: TYPE_FP32
  dims: [2]
}]
dynamic_batching {
  preferred_batch_size: [8, 16]
}
model_repository_agents {
  agents [{
    name: "checksum"
    parameters {
      key: "MD5:1/model.onnx"
      value: "524bbefcdea06d5e8971aa31929549aa"
    }
  }]
}
