name: "snbamsc_2dcnn_v"
platform: "tensorflow_savedmodel"


max_batch_size: 64

input [
  {
    name: "zero_padding2d_input"
    data_type: TYPE_FP32
    dims: [ 1148, 128, 1 ]
  }
]

output [
  {
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]


instance_group [
  { kind: KIND_GPU count: 1 }
]

