name: "snbamsc_2dcnn_u"
platform: "onnxruntime_onnx"


max_batch_size: 64

input [
  {
    name: "zero_padding2d_input"
    data_type: TYPE_FP32
    dims: [ 1149, 128, 1 ]
  }
]

output [
  {
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]


instance_group [
  { kind: KIND_GPU count: 1 }
]

model_repository_agents {
  agents [{
    name: "checksum"
    parameters {
      key: "MD5:1/model.onnx"
      value: "760d864455315bcadf47590b14ee03f9"
    }
  }]
}
